version: '3.8'
services:
  service1:
    build: .
    ports:
      - "5001:80"
    deploy:
      replicas: 2
      update-config:
        parallelism: 2
        delay: 10s
      restart-policy:
        condition: on-failure