version: '3.8'
services:
  service1:
    image: jerryonimo/lab5:latest
    ports:
      - "5001:80"
    deploy:
      replicas: 1
    networks:
     - my_network

networks:
  my_network:
    external: true    
